### ISSUE TITLE
TypeError: Cannot read property 'getRange' of null	

### ISSUE THREAD

**Issue by leo-smi** [mtrpires/covid-br-sheets#2]
Recebi esse erro:

Start | Function | Error Message | Trigger | End
-- | -- | -- | -- | --
4/5/20 5:12 PM | isUpdated | TypeError: Cannot read property 'getRange' of null | time-based | 4/5/20 5:12 PM

TypeError: Cannot read property 'getRange' of null (linha 57, arquivo "Código")

linha 57: var dt_current = sheet.getRange('E2').getValue();

**Comment by leo-smi** [comment]
Problema resolvido, eu não tinha criado todas as planilhas necessárias, consegui resolver o problema através do link https://stackoverflow.com/questions/54266510/typeerror-cannot-call-method-getrange-of-null-line-4-file-code

As sub-planilhas devem ser criadas conforme as variáveis (eu só tinha criado a aba 'Acumulo'):

// Guarda o nome de cada pasta na planilha
var sheet_dias = "Dias";
var sheet_acumulo = "Acumulo";
var sheet_semana = "Semana";
var sheet_regiao = "Regiao";
var sheet_geral = "Geral";
var sheet_mapa = "Mapa";

My bad

**Comment by mtrpires** [comment]
Sim, tem razão. Da forma como fiz você precisa criar as abas com antecedência. Vou adicionar uma rotina para criá-as caso elas não existam, como [aqui](https://stackoverflow.com/questions/22898501/create-a-new-sheet-in-a-google-sheets-with-google-apps-script)!

**Comment by mtrpires** [comment]
[Adicionei](https://github.com/mtrpires/covid-br-sheets/commit/aadd3cefac86af902d6a3d8e9497009f3b91f7db) uma função que verifica se as pastas foram criadas manualmente. Caso contrário, cria cada uma com o cabeçalho adequado.
