### ISSUE TITLE
Não funciona mais

### ISSUE THREAD

**Issue by rafaelsabino** [mtrpires/covid-br-sheets#3]
Era uma boa planilha que usava para acompanhar, porém não funciona mais. A secretaria de saúde alterou os dados e não é possível mais atualizar a planilha.

**Comment by JonerMello** [comment]
Estou com problema na refatoração para raspar os Estados e Regiões em:https://xx9p7hp1p7.execute-api.us-east-1.amazonaws.com/prod/PortalSintese

var sheet_new_Estado = "Sintese";
  function scrapeEstados() {
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(sheet_new_Estado);
    var request = UrlFetchApp.fetch(base_url + "Portal" + sheet_new_Estado, fetch_payload).getContentText();
    var json = JSON.parse(request);
    var rows = [],
        data; 
    for (i = 1; i < json.length; i++) {
      data = json[i];
      rows.push(data['_id']);
      rows.push(data['casosAcumulado']);
      rows.push(data['obitosAcumulado']);  
    }
    var dataRange = sheet.getDataRange();
    dataRange.setValues(rows); 
  }
Retorno:
[20-05-14 17:50:36:722 BRT] [Sul, 8741.0, 301.0, Sudeste, 78959.0, 6536.0, Centro-Oeste, 5417.0, 142.0, Nordeste, 61769.0, 3818.0, Norte, 34088.0, 2352.0]
[20-05-14 17:50:36:731 BRT] TypeError: Cannot read property 'getRange' of null

**Comment by mtrpires** [comment]
O governo agora disponibiliza os dados via CSV. Esse script se tornou obsoleto.
